### Creating an empty csv file for beta

In [5]:
import pandas as pd 
import numpy as np 


df = pd.DataFrame(columns=['k','beta_freq','beta_sem','beta_phon','numrat','denrat','num/den','phonl', 'phonh','freql','freqh', 'siml', 'simh'])

df.to_csv('beta/beta_CBM_no_rep.csv',index=False)

In [6]:
df

Empty DataFrame
Columns: [k, beta_freq, beta_sem, beta_phon, numrat, denrat, num/den, phonl, phonh, freql, freqh, siml, simh]
Index: []

In [7]:
df.loc[len(df)] = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'a', 'b']

In [8]:
df

,k,beta_freq,beta_sem,beta_phon,numrat,denrat,num/den,phonl,phonh,freql,freqh,siml,simh
0,a,b,c,d,e,f,g,h,i,j,k,a,b

In [1]:
import pandas as pd 
import numpy as np

/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_5885/1228117823.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
CBM_no_rep = pd.read_csv('beta/beta_CBM_no_rep.csv')
CBM_with_rep = pd.read_csv('beta/beta_CBM_with_rep.csv')

In [9]:
CBM_with_rep

,k,beta_freq,beta_sem,beta_phon,numrat,denrat,num/den,phonl,phonh,freql,freqh,siml,simh
0,0,0.312479,0.155874,0.602229,1.785222,7.995542e+02,0.002233,0.0001,[2.500e-01 1.250e-01 2.857e-01 1.000e-04 1.000...,6.389522,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.000100,[0.49938904 0.39305228 0.56460176 0.24979738 0...
1,1,0.312479,0.155874,0.602229,0.005831,7.978320e+01,0.000073,0.0001,[2.500e-01 1.250e-01 2.857e-01 1.000e-04 1.000...,5.864843,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.380401,[0.49938904 0.39305228 0.56460176 0.24979738 0...
2,2,0.312479,0.155874,0.602229,1.076639,1.508253e+02,0.007138,0.5000,[1.000e-04 1.250e-01 1.000e-04 1.000e-04 1.000...,6.723957,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.512455,[0.4327237 0.62746108 0.54461871 0.51022948 0...
3,3,0.312479,0.155874,0.602229,0.833756,1.485398e+02,0.005613,0.2857,[1.000e-04 2.500e-01 1.429e-01 1.667e-01 1.000...,6.250420,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.252715,[0.40408003 0.39204494 0.55527472 0.23544053 0...
4,4,0.312479,0.155874,0.602229,0.005963,1.176947e+02,0.000051,0.0001,[1.000e-04 1.000e-04 1.429e-01 1.429e-01 1.000...,7.119400,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.297928,[0.25368725 0.63956622 0.33508033 0.46470521 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
227875,22,5.355711,10.157215,0.083295,9952.470358,4.000645e+06,0.002488,0.1667,[2.500e-01 1.000e-04 1.429e-01 1.667e-01 1.667...,5.735626,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.352197,[1.88601635e-01 5.38258843e-01 3.11398804e-01 ...
227876,23,5.355711,10.157215,0.083295,20489.630460,4.135782e+06,0.004954,0.0001,[1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.667...,7.366227,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.500408,[0.52457839 0.554422 0.55174192 0.51098723 0...
227877,24,5.355711,10.157215,0.083295,6528.887978,3.849493e+06,0.001696,0.1667,[1.000e-04 2.500e-01 1.000e-04 1.000e-04 1.000...,5.301449,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.393125,[0.43702923 0.26467625 0.38531103 0.22456599 0...
227878,25,5.355711,10.157215,0.083295,4632.761413,3.507520e+06,0.001321,0.0001,[1.000e-04 1.250e-01 1.000e-04 1.000e-04 1.000...,5.580631,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.556165,[0.5792908 0.43144762 0.61696616 0.46696843 0...
227879,26,5.355711,10.157215,0.083295,8930.362886,4.793444e+06,0.001863,0.1111,[1.000e-04 1.000e-04 1.000e-04 1.111e-01 1.000...,5.656324,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.390160,[0.42624669 0.53603838 0.54988081 0.72508962 0...

In [6]:
CBM_with_rep.describe()

/Users/mingikang/miniforge3/envs/ML/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/mingikang/miniforge3/envs/ML/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,k,beta_freq,beta_sem,beta_phon,numrat,denrat,num/den,phonl,freql,siml
count,227880.000000,2.278800e+05,2.278800e+05,2.278800e+05,2.250960e+05,2.212200e+05,177488.000000,227880.000000,227880.000000,227880.000000
mean,13.000000,-6.834297e+54,3.495873e+59,-1.392216e+58,inf,inf,0.018565,0.186270,6.266965,0.476328
std,7.788898,1.683254e+56,5.810465e+60,2.314000e+59,NaN,NaN,0.090373,0.286984,0.627267,0.209032
min,0.000000,-5.973131e+57,1.926613e-04,-6.696896e+60,0.000000e+00,0.000000e+00,0.000000,0.000100,5.301449,0.000100
25%,6.000000,8.250340e-01,2.676564e+00,-1.384290e+02,3.137240e+00,1.258005e+03,0.001703,0.000100,5.656324,0.341778
50%,13.000000,5.355588e+00,4.578663e+00,4.651165e-02,7.184031e+03,2.391550e+06,0.002638,0.111100,6.144792,0.474428
75%,20.000000,6.611596e+00,3.474672e+03,1.064909e-01,6.096339e+04,1.575956e+07,0.005105,0.166700,6.723957,0.586883
max,26.000000,7.775788e+56,1.681547e+62,1.070857e+00,inf,inf,1.000000,1.000000,7.366227,1.000000

In [15]:
mask = CBM_with_rep['beta_freq'] > 100
CBM_with_rep[mask]

,k,beta_freq,beta_sem,beta_phon,numrat,denrat,num/den,phonl,phonh,freql,freqh,siml,simh
143316,0,1.321581e+02,1.730388e+07,-6.891030e+05,2.812758e+106,1.596924e+122,1.761360e-16,0.0001,[2.500e-01 1.250e-01 2.857e-01 1.000e-04 1.000...,6.389522,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.000100,[0.49938904 0.39305228 0.56460176 0.24979738 0...
143317,1,1.321581e+02,1.730388e+07,-6.891030e+05,3.398373e+101,1.596924e+122,2.128074e-21,0.0001,[2.500e-01 1.250e-01 2.857e-01 1.000e-04 1.000...,5.864843,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.380401,[0.49938904 0.39305228 0.56460176 0.24979738 0...
143318,2,1.321581e+02,1.730388e+07,-6.891030e+05,2.383966e+109,1.596924e+122,1.492848e-13,0.5000,[1.000e-04 1.250e-01 1.000e-04 1.000e-04 1.000...,6.723957,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.512455,[0.4327237 0.62746108 0.54461871 0.51022948 0...
143319,3,1.321581e+02,1.730388e+07,-6.891030e+05,1.533964e+105,1.596924e+122,9.605740e-18,0.2857,[1.000e-04 2.500e-01 1.429e-01 1.667e-01 1.000...,6.250420,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.252715,[0.40408003 0.39204494 0.55527472 0.23544053 0...
143320,4,1.321581e+02,1.730388e+07,-6.891030e+05,4.542151e+112,1.596924e+122,2.844312e-10,0.0001,[1.000e-04 1.000e-04 1.429e-01 1.429e-01 1.000...,7.119400,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.297928,[0.25368725 0.63956622 0.33508033 0.46470521 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
225283,22,6.037348e+56,1.681547e+62,-6.696896e+60,inf,inf,NaN,0.1667,[2.500e-01 1.000e-04 1.429e-01 1.667e-01 1.667...,5.735626,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.352197,[1.88601635e-01 5.38258843e-01 3.11398804e-01 ...
225284,23,6.037348e+56,1.681547e+62,-6.696896e+60,inf,inf,NaN,0.0001,[1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.667...,7.366227,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.500408,[0.52457839 0.554422 0.55174192 0.51098723 0...
225285,24,6.037348e+56,1.681547e+62,-6.696896e+60,inf,inf,NaN,0.1667,[1.000e-04 2.500e-01 1.000e-04 1.000e-04 1.000...,5.301449,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.393125,[0.43702923 0.26467625 0.38531103 0.22456599 0...
225286,25,6.037348e+56,1.681547e+62,-6.696896e+60,inf,inf,NaN,0.0001,[1.000e-04 1.250e-01 1.000e-04 1.000e-04 1.000...,5.580631,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.556165,[0.5792908 0.43144762 0.61696616 0.46696843 0...
225287,26,6.037348e+56,1.681547e+62,-6.696896e+60,inf,inf,NaN,0.1111,[1.000e-04 1.000e-04 1.000e-04 1.111e-01 1.000...,5.656324,[5.54479829 5.40041537 5.71416289 4.95691723 5...,0.390160,[0.42624669 0.53603838 0.54988081 0.72508962 0...

In [18]:
CBM_with_rep[143316: 145000].to_csv('beta/beta_CBM_with_rep_143316_145000.csv')

In [19]:
CBM_with_rep[0: 100].to_csv('beta/beta_CBM_with_rep_0_100.csv')

## Manual calculations

### the beginning calculations

In [95]:
df = pd.read_csv('beta/beta_CBM_with_rep_0_100.csv')
row = df.iloc[1].tolist()[1:]
print(row)
print(len(row))

[1, 0.3124793873575103, 0.1558735789830378, 0.6022285757322337, 0.0058307001938893, 79.78319783444225, 7.308180609642378e-05, 0.0001, '[2.500e-01 1.250e-01 2.857e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.429e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 2.500e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 2.000e-01 1.000e-04 2.500e-01\n 1.000e-04 1.000e-04 1.000e-04 2.000e-01 1.111e-01 1.429e-01 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 2.000e-01 1.000e-04 1.000e-04 1.000e-04\n 2.500e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.250e-01 1.429e-01 2.000e-01 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 2.500e-01 1.000e-04 1.250e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.667e-01 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 5.000e-01 2.000e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.250e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 2.500e-01 2.500e-01 1.000e-04\n 1.429e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.667e-01 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 5.000e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.667e-01 1.000e-04 2.500e-01\n 1.000e-04 1.000e-04 1.667e-01 1.000e-04 2.857e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 2.000e-01 1.000e-04 1.000e-04 1.000e-04 2.000e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 2.500e-01 1.000e-04 1.250e-01 1.250e-01 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 5.000e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 9.090e-02 2.500e-01 2.500e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.250e-01 1.000e-04 2.000e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.667e-01 1.000e-04 1.000e-04 3.333e-01 1.000e-04 1.000e-04\n 1.429e-01 2.500e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 2.000e-01 1.000e-04 2.500e-01 1.667e-01 2.000e-01 2.000e-01 1.000e-04\n 1.000e-04 1.667e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.667e-01\n 2.000e-01 2.000e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.250e-01 1.000e-04 1.000e-04 2.500e-01 1.667e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 2.500e-01 1.000e-04 1.000e-04\n 1.000e-04 1.667e-01 1.667e-01 1.000e-04 1.000e-04 1.667e-01 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.429e-01 1.000e-04 2.500e-01\n 1.667e-01 1.000e-04 1.000e-04 1.667e-01 1.250e-01 2.500e-01 1.000e-04\n 1.000e-04 1.000e-04 2.500e-01 2.000e-01 2.000e-01 1.000e-04 1.000e-04\n 1.000e-04 1.429e-01 1.000e-04 1.000e-04 1.429e-01 1.000e-04 1.250e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 2.500e-01 1.000e-04 2.500e-01\n 2.500e-01 2.000e-01 2.500e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.667e-01 2.000e-01 1.000e-04\n 2.500e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 3.333e-01 1.111e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.250e-01 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 2.000e-01 1.000e-04 1.111e-01 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 2.000e-01 1.000e-04 1.000e-04 1.429e-01 1.000e-04 1.000e-04\n 1.429e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 2.000e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 4.000e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 2.500e-01 1.429e-01 1.429e-01 1.429e-01 1.000e-04\n 1.000e-04 2.000e-01 1.667e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 2.500e-01 1.667e-01 2.000e-01 3.333e-01 1.667e-01 4.000e-01\n 1.000e-04 1.000e-04 2.500e-01 1.000e+00 1.667e-01 2.500e-01 1.667e-01\n 2.500e-01 3.750e-01 4.000e-01 2.500e-01 2.500e-01 2.500e-01 2.500e-01\n 2.500e-01 2.000e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 5.000e-01\n 2.000e-01 1.000e-04 1.667e-01 1.000e-04 1.429e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.667e-01 2.000e-01 1.429e-01 1.000e-04 1.000e-04\n 1.000e-04 1.429e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.429e-01\n 1.000e-04 1.000e-04 1.000e-04 1.250e-01 1.000e-04 1.000e-04 2.500e-01\n 1.429e-01 1.429e-01 1.000e-04 2.500e-01 1.000e-04 2.500e-01 1.000e-04\n 1.000e-04 1.000e-04 1.111e-01 1.000e-04 2.500e-01 1.000e-04 1.000e-04\n 1.000e-04]', 5.864843201, '[5.54479829 5.40041537 5.71416289 4.95691723 5.19427562 5.36416061\n 6.4261461  5.84517062 6.01239891 5.81312644 6.57583615 5.36663211\n 7.27868644 5.80313196 5.84991915 4.87676037 6.63150079 6.52730735\n 5.38246012 7.36622693 6.27319301 6.52393588 6.02186668 7.11940024\n 5.77813388 4.91087509 5.48689924 5.31324274 5.42827413 5.90912687\n 5.34874867 5.83892776 5.03831808 6.47724255 6.71047101 6.15191934\n 6.95347854 5.40648568 4.9575594  5.84937826 4.87166049 5.80942435\n 5.58832438 6.02804311 6.22570901 5.41009701 6.36702961 6.12305154\n 5.40936834 5.80587722 5.92785316 4.34588321 6.70466853 5.66047842\n 5.67599086 7.01314336 5.82700462 6.99145703 4.98628344 4.46372879\n 5.34309729 5.24019718 6.13538329 6.0950762  4.98597405 6.82758559\n 4.5937954  5.35425638 5.14961934 5.7629695  5.6749759  5.0944292\n 6.34660546 5.01198044 6.29438156 5.16478099 5.33323965 6.05355398\n 5.4567546  6.33169629 5.3132174  4.89617335 6.67904722 6.51714732\n 6.00734017 6.15811632 6.40422836 5.1067313  5.42952458 5.98034976\n 5.74138405 6.39803797 5.72680705 5.69702959 5.00798662 4.75673497\n 7.40325542 6.70698374 4.13436839 6.93246286 5.22334535 6.34802277\n 7.25611403 6.98735549 5.8648432  6.08020714 6.01842169 4.70769789\n 5.25922823 6.32439606 6.4776833  6.29606092 4.74550419 6.4396388\n 5.16028241 6.18352152 6.64085425 5.81821203 5.53780525 4.97979413\n 6.36366029 6.13956584 5.40300206 5.49800161 5.93662582 5.73324703\n 5.5591762  5.53151085 5.22067805 5.89118162 5.16926875 7.34481426\n 6.60415431 5.81714343 6.59752483 5.421176   7.02917652 5.16993294\n 5.41156079 6.05982081 6.84972718 5.86263101 4.30033457 6.31934657\n 6.22332536 6.32233364 4.29673099 5.20884966 5.69120442 5.34520312\n 6.03987712 6.83232481 5.91434792 5.09528445 5.25936688 6.36583846\n 6.23189196 4.54084231 4.93771343 5.47526285 6.30195579 5.59729141\n 5.65709316 5.62931376 5.2365423  5.59953703 5.73562604 4.81622804\n 5.74121071 5.69974236 5.6539762  4.53131283 6.0966139  5.75274123\n 5.42877766 5.30317661 5.23774475 6.38789858 6.50909199 6.38458152\n 5.30144889 5.48215154 6.44552325 6.01428148 5.80200431 6.00100423\n 5.25839062 6.1191846  6.06158667 4.55894845 7.39671054 5.99387075\n 7.98965008 5.42222367 5.72994274 5.52378027 5.28499889 5.12002084\n 4.82558189 6.51956353 7.19745311 5.36467667 5.15519024 4.69350711\n 5.70257958 6.55394513 5.22457968 5.56621823 4.35285756 6.77461447\n 5.19281826 5.88303424 5.85594476 6.17394082 6.5534405  5.72304581\n 4.67605313 4.67003236 6.67546488 5.90347634 5.97693842 6.32090595\n 5.66947123 4.73326951 5.87598562 5.12563739 6.72395708 5.25925214\n 6.27733182 5.89522027 5.26914153 4.58063991 5.98910839 5.79519503\n 5.50136056 5.51662262 5.51244958 5.55509566 5.17378047 5.29660816\n 5.36434083 5.91173061 8.40582899 6.29051474 4.91820863 5.34128611\n 5.05999863 5.04717748 5.51528026 5.8723754  6.64058866 5.28218465\n 5.30666516 5.67333338 5.21399827 4.84604625 5.79285026 5.20351154\n 6.34759598 4.94896038 4.9844733  6.74986543 6.40192655 6.27941368\n 6.50045384 5.97775423 5.30054549 6.0265492  6.09035471 5.82972885\n 6.77684605 6.27403956 6.21093915 5.22988141 5.24813518 5.34251151\n 5.55104113 5.46032341 5.45678191 5.9647328  4.74836636 5.17316295\n 5.21287181 5.65358681 4.98490069 5.85768341 6.24711561 6.33101933\n 6.16528113 6.06514446 6.01909426 5.88628481 4.71569422 4.86887357\n 5.92109627 5.86740973 6.00263338 5.58192805 6.25042049 5.98829937\n 5.46087079 7.92691552 4.60659631 5.61970467 6.32053967 6.61154297\n 6.10484819 5.22249797 6.31138805 5.30314204 6.53451663 5.88079931\n 6.1797195  5.35560475 5.58063079 6.42252681 5.23339213 5.44040999\n 6.2976058  5.8927639  5.00730387 4.92727795 5.30037154 4.85464605\n 5.21953999 5.68211438 6.03109081 5.2925241  5.85883485 6.56862865\n 6.40924176 6.76646341 5.068364   5.64832097 6.2387933  7.101132\n 4.49780013 4.621249   3.92931673 5.76409241 5.6563244  5.50684178\n 5.68899257 6.52619707 6.04796568 5.4965159  5.70385517 5.82336205\n 5.41027096 6.53599766 5.1590285  5.60137761 6.7887631  6.38005632\n 5.53223317 6.05460386 6.92417287 5.70115767 6.54277254 5.54581041\n 6.17749985 5.1888582  5.58390577 5.61302636 5.09154034 5.60361632\n 5.6658248  5.59460578 5.85380525 6.61507849 5.33162567 5.34684568\n 6.12976302 5.35852874 6.06375281 6.28164913 6.14113578 4.8769795\n 4.83454786 6.08084034 5.78537611 5.76888884 5.31226201 5.49266263\n 5.87640203 6.13540142 5.48775755 5.52855421 5.03187281 6.40307057\n 6.23145965 6.72486439 6.08194504 5.25062734 5.20892215 5.34137714\n 4.94463564 5.62374431 5.57888551 5.42137191 5.6849898  6.01822018\n 6.38952206 5.02977731 5.88589528 5.79337125 4.73203975 4.08845504\n 5.5450113  6.39341672 5.38398941 4.66830203 4.85497367 6.76776835\n 6.2297581  5.57345298 5.53606327 5.90222162 5.62709434 5.48204277\n 5.63386924 5.41780372 5.61881972 5.78342259 5.50157956 5.59878941\n 6.33861504 4.93445805 5.47692723 5.14602565 5.8536605  5.47753653\n 5.4461751  6.74554898 4.52057523 5.15610676 6.26570392 7.86615585\n 5.02871355 5.49635113 5.58929711 6.38306367 5.85059294 5.19362542\n 4.27870788 5.56168919 5.94341091 6.42539563 6.22546462 5.41884962\n 6.53817281 5.8220294  6.31354138 6.37252151 6.51178019 6.79845506\n 8.14512647 6.53085142 7.28454499 8.1286163  5.81842254 6.71528817\n 6.14479208]', 0.3804007725381781, '[0.49938904 0.39305228 0.56460176 0.24979738 0.28217551 0.34929894\n 0.50139696 0.48264412 0.51625779 0.35779084 0.40271439 0.47539001\n 0.31364476 0.4670242  0.31732986 0.42592225 0.19123095 0.35715744\n 0.35399132 0.25669001 0.34705417 0.3153922  0.49765555 0.4771945\n 0.51666508 0.45060853 0.42846129 0.46967466 0.38224313 0.5341891\n 0.42070936 0.44255956 0.42173448 0.33971355 0.38016196 0.49965582\n 0.58630306 0.45859309 0.32876009 0.3877416  0.3979551  0.29452816\n 0.33577278 0.33269913 0.26318629 0.48951237 0.48866769 0.36013172\n 0.26000349 0.39880235 0.3812283  0.35538603 0.2389608  0.47755624\n 0.37871874 0.59976153 0.36073374 0.29180965 0.4338842  0.41740849\n 0.27194739 0.3593068  0.42380868 0.39882775 0.44473671 0.43898408\n 0.4654036  0.30500928 0.42630976 0.29066689 0.47595761 0.34691618\n 0.45784983 0.32194325 0.33170234 0.41524572 0.44581731 0.35434847\n 0.15271598 0.21118557 0.46333202 0.38904187 0.37604176 0.28317325\n 0.49715229 0.50138673 0.47143259 0.36281855 0.50777526 0.36743281\n 0.57551893 0.48877866 0.48373219 0.40088824 0.44112274 0.42815162\n 0.15684488 0.52561356 0.24114885 0.36903706 0.37032617 0.58493525\n 0.54656832 0.42897993 0.38040077 0.24778876 0.38755082 0.44501033\n 0.36195828 0.51158335 0.42879438 0.2588698  0.46723188 0.48340922\n 0.49867308 0.36013094 0.47497761 0.46174793 0.38857972 0.48098565\n 0.46754799 0.46510568 0.34487737 0.5009822  0.56397328 0.3543065\n 0.40673866 0.4613312  0.38905596 0.46315928 0.28830975 0.44983053\n 0.47087864 0.48292533 0.32425203 0.37115982 0.32180676 0.48643509\n 0.39230303 0.40647063 0.54763232 0.46265686 0.28534676 0.46693282\n 0.31640954 0.31168794 0.36602008 0.34811217 0.24229468 0.36702835\n 0.40362387 0.40479113 0.13872621 0.26345273 0.41538197 0.56689326\n 0.41566561 0.3762477  0.49340067 0.4394734  0.37629781 0.20504412\n 0.39374825 0.52972776 0.38273825 0.29761294 0.47664454 0.45938757\n 0.45487454 0.38555406 0.4617614  0.48428613 0.41758518 0.33610977\n 0.13430649 0.38886484 0.17901085 0.56204113 0.29352569 0.48553454\n 0.518151   0.50960812 0.52409257 0.42182042 0.4185198  0.3565483\n 0.5104222  0.44122936 0.31683126 0.46296244 0.25652411 0.49524575\n 0.26125044 0.47638072 0.33925113 0.44083941 0.50694569 0.54312653\n 0.47062182 0.44645908 0.34174553 0.60311544 0.34104401 0.40654912\n 0.56998111 0.34448869 0.27507225 0.59248512 0.38521706 0.37082996\n 0.50615733 0.38680788 0.39427843 0.30597846 0.30645402 0.21187443\n 0.38037305 0.38197224 0.38764624 0.37678424 0.45554552 0.33597934\n 0.41605184 0.45224793 0.57240001 0.40420628 0.63715923 0.48389614\n 0.54798964 0.46764357 0.40435277 0.21885673 0.43905627 0.45319166\n 0.43038713 0.40153829 0.53959454 0.24254268 0.43926322 0.50571213\n 0.43943736 0.41979652 0.39291892 0.31916475 0.40932763 0.61014458\n 0.51960717 0.40173633 0.31974675 0.25871366 0.39317954 0.42113008\n 0.40788178 0.54631586 0.46935517 0.28729743 0.27599778 0.31264138\n 0.40299512 0.2628075  0.48508478 0.28781431 0.5783559  0.47317538\n 0.51010197 0.55139271 0.2346785  0.43046587 0.32553033 0.2607733\n 0.55785771 0.249442   0.23454964 0.37076487 0.42075005 0.3818002\n 0.3748194  0.15974843 0.20430708 0.2651121  0.40723294 0.46314029\n 0.4239376  0.35839274 0.42358318 0.40613808 0.48996164 0.41849399\n 0.35702307 0.33902944 0.29516511 0.60558804 0.21477395 0.38389937\n 0.38550857 0.42728654 0.40582218 0.40652892 0.31927979 0.51823564\n 0.26512122 0.28237144 0.49584295 0.55198832 0.14686962 0.49377493\n 0.52149058 0.31991581 0.3914851  0.40830018 0.15219631 0.44201755\n 0.25114049 0.44105472 0.37318572 0.33555655 0.25136385 0.47129117\n 0.29239281 0.21258366 0.55361937 0.24602233 0.44726495 0.37877715\n 0.52219122 0.45435939 0.50351221 0.41720265 0.43115457 0.58818605\n 0.39179413 0.45514054 0.40570764 0.47853393 0.44524242 0.20824962\n 0.31367051 0.49445672 0.56064673 0.41090776 0.47004423 0.47597625\n 0.4550135  0.38420536 0.46345875 0.39640231 0.42337578 0.19354813\n 0.37504802 0.45031096 0.29075096 0.51989901 0.3791604  0.44155998\n 0.2981352  0.46158244 0.35772838 0.40761253 0.35887065 0.33801128\n 0.4497198  0.39714028 0.3629864  0.56414814 0.35703518 0.22267849\n 0.31838847 0.22882842 0.49835933 0.5385183  0.42366345 0.46814246\n 0.34050133 0.48873664 0.54412422 0.37726149 0.15357791 0.43701353\n 0.40744805 0.5602257  0.617183   0.44776676 0.41123989 0.40002999\n 0.34421012 0.22006825 0.47735859 0.32814275 0.39013785 0.49806074\n 0.24318069 0.24219131 0.49470545 0.51830093 0.41392418 0.27543923\n 0.44216836 0.37235984 0.36905458 0.38657276 0.51229759 0.23054795\n 1.         0.47911198 0.52175571 0.47076358 0.28385831 0.33544588\n 0.31778793 0.48461983 0.35952161 0.33344736 0.30989103 0.3949117\n 0.37819282 0.37231449 0.46012684 0.32059956 0.40391387 0.50372852\n 0.39326237 0.54550083 0.38429373 0.36475192 0.37983694 0.54986948\n 0.45329855 0.36710511 0.27704582 0.38186398 0.40364581 0.49974917\n 0.20705893 0.5379345  0.28266112 0.48529591 0.61444431 0.28598076\n 0.43196635 0.43975012 0.4466945  0.43548002 0.38582607 0.54147148\n 0.43144955 0.55537415 0.20585914 0.22995888 0.30973131 0.36881204\n 0.35709276 0.46930278 0.25294084 0.53985943 0.27390313 0.30005384\n 0.20799117 0.24131116 0.31473799 0.27487912 0.30930793 0.30604629\n 0.33609347]']
13

In [96]:
# k	 beta_freq	beta_sem	beta_phon	numrat	denrat	num/den	phonl	phonh	freql	freqh	siml	simh
# 0      1          2           3       4       5       6       7       8       9       10      11      12
'''
if phoncue in ["local","global"]:
    numrat = pow(freql[k],beta[0])*pow(phonl[k],beta[2])*pow(siml[k],beta[1])
    denrat = sum(pow(freqh[k],beta[0])*pow(phonh[k],beta[2])*pow(simh[k],beta[1]))
else:
    numrat = pow(freql[k],beta[0]) * pow(siml[k],beta[1])
    denrat = sum(pow(freqh[k],beta[0]) * pow(simh[k],beta[1]))
'''

numrat = (row[9]**row[1]) * (row[7]**row[3]) * (row[11]**row[2])
print("calculated numrat: ", numrat)
print("numrat: ", row[4])

calculated numrat:  0.005830700193889325
numrat:  0.0058307001938893

In [97]:
row[8] = row[8][1:-1].replace('\n', ' ').split(' ')
row[8] = [i for i in row[8] if i != '']
row[8] = [float(i) for i in row[8]]
row[10] = row[10][1:-1].replace('\n', ' ').split(' ')
row[10] = [i for i in row[10] if i != '']
row[10] = [float(i) for i in row[10]]
row[12] = row[12][1:-1].replace('\n', ' ').split(' ')
row[12] = [i for i in row[12] if i != '']
row[12] = [float(i) for i in row[12]]

In [98]:
print(row[8])
print(len(row[8]))
print(row[10])
print(len(row[10]))
print(row[12])
print(len(row[12]))

[0.25, 0.125, 0.2857, 0.0001, 0.0001, 0.0001, 0.0001, 0.1429, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.0001, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.25, 0.0001, 0.0001, 0.0001, 0.2, 0.1111, 0.1429, 0.0001, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.0001, 0.0001, 0.25, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.125, 0.1429, 0.2, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.0001, 0.125, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.1667, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.5, 0.2, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.125, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.25, 0.0001, 0.1429, 0.0001, 0.0001, 0.0001, 0.0001, 0.1667, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.5, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.1667, 0.0001, 0.25, 0.0001, 0.0001, 0.1667, 0.0001, 0.2857, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.0001, 0.125, 0.125, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.5, 0.0001, 0.0001, 0.0001, 0.0001, 0.0909, 0.25, 0.25, 0.0001, 0.0001, 0.0001, 0.0001, 0.125, 0.0001, 0.2, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.1667, 0.0001, 0.0001, 0.3333, 0.0001, 0.0001, 0.1429, 0.25, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.25, 0.1667, 0.2, 0.2, 0.0001, 0.0001, 0.1667, 0.0001, 0.0001, 0.0001, 0.0001, 0.1667, 0.2, 0.2, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.125, 0.0001, 0.0001, 0.25, 0.1667, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.0001, 0.0001, 0.0001, 0.1667, 0.1667, 0.0001, 0.0001, 0.1667, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.1429, 0.0001, 0.25, 0.1667, 0.0001, 0.0001, 0.1667, 0.125, 0.25, 0.0001, 0.0001, 0.0001, 0.25, 0.2, 0.2, 0.0001, 0.0001, 0.0001, 0.1429, 0.0001, 0.0001, 0.1429, 0.0001, 0.125, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.0001, 0.25, 0.25, 0.2, 0.25, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.1667, 0.2, 0.0001, 0.25, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.3333, 0.1111, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.125, 0.0001, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.1111, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.0001, 0.1429, 0.0001, 0.0001, 0.1429, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.2, 0.0001, 0.0001, 0.0001, 0.0001, 0.4, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.1429, 0.1429, 0.1429, 0.0001, 0.0001, 0.2, 0.1667, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.25, 0.1667, 0.2, 0.3333, 0.1667, 0.4, 0.0001, 0.0001, 0.25, 1.0, 0.1667, 0.25, 0.1667, 0.25, 0.375, 0.4, 0.25, 0.25, 0.25, 0.25, 0.25, 0.2, 0.0001, 0.0001, 0.0001, 0.0001, 0.5, 0.2, 0.0001, 0.1667, 0.0001, 0.1429, 0.0001, 0.0001, 0.0001, 0.0001, 0.1667, 0.2, 0.1429, 0.0001, 0.0001, 0.0001, 0.1429, 0.0001, 0.0001, 0.0001, 0.0001, 0.1429, 0.0001, 0.0001, 0.0001, 0.125, 0.0001, 0.0001, 0.25, 0.1429, 0.1429, 0.0001, 0.25, 0.0001, 0.25, 0.0001, 0.0001, 0.0001, 0.1111, 0.0001, 0.25, 0.0001, 0.0001, 0.0001]
463
[5.54479829, 5.40041537, 5.71416289, 4.95691723, 5.19427562, 5.36416061, 6.4261461, 5.84517062, 6.01239891, 5.81312644, 6.57583615, 5.36663211, 7.27868644, 5.80313196, 5.84991915, 4.87676037, 6.63150079, 6.52730735, 5.38246012, 7.36622693, 6.27319301, 6.52393588, 6.02186668, 7.11940024, 5.77813388, 4.91087509, 5.48689924, 5.31324274, 5.42827413, 5.90912687, 5.34874867, 5.83892776, 5.03831808, 6.47724255, 6.71047101, 6.15191934, 6.95347854, 5.40648568, 4.9575594, 5.84937826, 4.87166049, 5.80942435, 5.58832438, 6.02804311, 6.22570901, 5.41009701, 6.36702961, 6.12305154, 5.40936834, 5.80587722, 5.92785316, 4.34588321, 6.70466853, 5.66047842, 5.67599086, 7.01314336, 5.82700462, 6.99145703, 4.98628344, 4.46372879, 5.34309729, 5.24019718, 6.13538329, 6.0950762, 4.98597405, 6.82758559, 4.5937954, 5.35425638, 5.14961934, 5.7629695, 5.6749759, 5.0944292, 6.34660546, 5.01198044, 6.29438156, 5.16478099, 5.33323965, 6.05355398, 5.4567546, 6.33169629, 5.3132174, 4.89617335, 6.67904722, 6.51714732, 6.00734017, 6.15811632, 6.40422836, 5.1067313, 5.42952458, 5.98034976, 5.74138405, 6.39803797, 5.72680705, 5.69702959, 5.00798662, 4.75673497, 7.40325542, 6.70698374, 4.13436839, 6.93246286, 5.22334535, 6.34802277, 7.25611403, 6.98735549, 5.8648432, 6.08020714, 6.01842169, 4.70769789, 5.25922823, 6.32439606, 6.4776833, 6.29606092, 4.74550419, 6.4396388, 5.16028241, 6.18352152, 6.64085425, 5.81821203, 5.53780525, 4.97979413, 6.36366029, 6.13956584, 5.40300206, 5.49800161, 5.93662582, 5.73324703, 5.5591762, 5.53151085, 5.22067805, 5.89118162, 5.16926875, 7.34481426, 6.60415431, 5.81714343, 6.59752483, 5.421176, 7.02917652, 5.16993294, 5.41156079, 6.05982081, 6.84972718, 5.86263101, 4.30033457, 6.31934657, 6.22332536, 6.32233364, 4.29673099, 5.20884966, 5.69120442, 5.34520312, 6.03987712, 6.83232481, 5.91434792, 5.09528445, 5.25936688, 6.36583846, 6.23189196, 4.54084231, 4.93771343, 5.47526285, 6.30195579, 5.59729141, 5.65709316, 5.62931376, 5.2365423, 5.59953703, 5.73562604, 4.81622804, 5.74121071, 5.69974236, 5.6539762, 4.53131283, 6.0966139, 5.75274123, 5.42877766, 5.30317661, 5.23774475, 6.38789858, 6.50909199, 6.38458152, 5.30144889, 5.48215154, 6.44552325, 6.01428148, 5.80200431, 6.00100423, 5.25839062, 6.1191846, 6.06158667, 4.55894845, 7.39671054, 5.99387075, 7.98965008, 5.42222367, 5.72994274, 5.52378027, 5.28499889, 5.12002084, 4.82558189, 6.51956353, 7.19745311, 5.36467667, 5.15519024, 4.69350711, 5.70257958, 6.55394513, 5.22457968, 5.56621823, 4.35285756, 6.77461447, 5.19281826, 5.88303424, 5.85594476, 6.17394082, 6.5534405, 5.72304581, 4.67605313, 4.67003236, 6.67546488, 5.90347634, 5.97693842, 6.32090595, 5.66947123, 4.73326951, 5.87598562, 5.12563739, 6.72395708, 5.25925214, 6.27733182, 5.89522027, 5.26914153, 4.58063991, 5.98910839, 5.79519503, 5.50136056, 5.51662262, 5.51244958, 5.55509566, 5.17378047, 5.29660816, 5.36434083, 5.91173061, 8.40582899, 6.29051474, 4.91820863, 5.34128611, 5.05999863, 5.04717748, 5.51528026, 5.8723754, 6.64058866, 5.28218465, 5.30666516, 5.67333338, 5.21399827, 4.84604625, 5.79285026, 5.20351154, 6.34759598, 4.94896038, 4.9844733, 6.74986543, 6.40192655, 6.27941368, 6.50045384, 5.97775423, 5.30054549, 6.0265492, 6.09035471, 5.82972885, 6.77684605, 6.27403956, 6.21093915, 5.22988141, 5.24813518, 5.34251151, 5.55104113, 5.46032341, 5.45678191, 5.9647328, 4.74836636, 5.17316295, 5.21287181, 5.65358681, 4.98490069, 5.85768341, 6.24711561, 6.33101933, 6.16528113, 6.06514446, 6.01909426, 5.88628481, 4.71569422, 4.86887357, 5.92109627, 5.86740973, 6.00263338, 5.58192805, 6.25042049, 5.98829937, 5.46087079, 7.92691552, 4.60659631, 5.61970467, 6.32053967, 6.61154297, 6.10484819, 5.22249797, 6.31138805, 5.30314204, 6.53451663, 5.88079931, 6.1797195, 5.35560475, 5.58063079, 6.42252681, 5.23339213, 5.44040999, 6.2976058, 5.8927639, 5.00730387, 4.92727795, 5.30037154, 4.85464605, 5.21953999, 5.68211438, 6.03109081, 5.2925241, 5.85883485, 6.56862865, 6.40924176, 6.76646341, 5.068364, 5.64832097, 6.2387933, 7.101132, 4.49780013, 4.621249, 3.92931673, 5.76409241, 5.6563244, 5.50684178, 5.68899257, 6.52619707, 6.04796568, 5.4965159, 5.70385517, 5.82336205, 5.41027096, 6.53599766, 5.1590285, 5.60137761, 6.7887631, 6.38005632, 5.53223317, 6.05460386, 6.92417287, 5.70115767, 6.54277254, 5.54581041, 6.17749985, 5.1888582, 5.58390577, 5.61302636, 5.09154034, 5.60361632, 5.6658248, 5.59460578, 5.85380525, 6.61507849, 5.33162567, 5.34684568, 6.12976302, 5.35852874, 6.06375281, 6.28164913, 6.14113578, 4.8769795, 4.83454786, 6.08084034, 5.78537611, 5.76888884, 5.31226201, 5.49266263, 5.87640203, 6.13540142, 5.48775755, 5.52855421, 5.03187281, 6.40307057, 6.23145965, 6.72486439, 6.08194504, 5.25062734, 5.20892215, 5.34137714, 4.94463564, 5.62374431, 5.57888551, 5.42137191, 5.6849898, 6.01822018, 6.38952206, 5.02977731, 5.88589528, 5.79337125, 4.73203975, 4.08845504, 5.5450113, 6.39341672, 5.38398941, 4.66830203, 4.85497367, 6.76776835, 6.2297581, 5.57345298, 5.53606327, 5.90222162, 5.62709434, 5.48204277, 5.63386924, 5.41780372, 5.61881972, 5.78342259, 5.50157956, 5.59878941, 6.33861504, 4.93445805, 5.47692723, 5.14602565, 5.8536605, 5.47753653, 5.4461751, 6.74554898, 4.52057523, 5.15610676, 6.26570392, 7.86615585, 5.02871355, 5.49635113, 5.58929711, 6.38306367, 5.85059294, 5.19362542, 4.27870788, 5.56168919, 5.94341091, 6.42539563, 6.22546462, 5.41884962, 6.53817281, 5.8220294, 6.31354138, 6.37252151, 6.51178019, 6.79845506, 8.14512647, 6.53085142, 7.28454499, 8.1286163, 5.81842254, 6.71528817, 6.14479208]
463
[0.49938904, 0.39305228, 0.56460176, 0.24979738, 0.28217551, 0.34929894, 0.50139696, 0.48264412, 0.51625779, 0.35779084, 0.40271439, 0.47539001, 0.31364476, 0.4670242, 0.31732986, 0.42592225, 0.19123095, 0.35715744, 0.35399132, 0.25669001, 0.34705417, 0.3153922, 0.49765555, 0.4771945, 0.51666508, 0.45060853, 0.42846129, 0.46967466, 0.38224313, 0.5341891, 0.42070936, 0.44255956, 0.42173448, 0.33971355, 0.38016196, 0.49965582, 0.58630306, 0.45859309, 0.32876009, 0.3877416, 0.3979551, 0.29452816, 0.33577278, 0.33269913, 0.26318629, 0.48951237, 0.48866769, 0.36013172, 0.26000349, 0.39880235, 0.3812283, 0.35538603, 0.2389608, 0.47755624, 0.37871874, 0.59976153, 0.36073374, 0.29180965, 0.4338842, 0.41740849, 0.27194739, 0.3593068, 0.42380868, 0.39882775, 0.44473671, 0.43898408, 0.4654036, 0.30500928, 0.42630976, 0.29066689, 0.47595761, 0.34691618, 0.45784983, 0.32194325, 0.33170234, 0.41524572, 0.44581731, 0.35434847, 0.15271598, 0.21118557, 0.46333202, 0.38904187, 0.37604176, 0.28317325, 0.49715229, 0.50138673, 0.47143259, 0.36281855, 0.50777526, 0.36743281, 0.57551893, 0.48877866, 0.48373219, 0.40088824, 0.44112274, 0.42815162, 0.15684488, 0.52561356, 0.24114885, 0.36903706, 0.37032617, 0.58493525, 0.54656832, 0.42897993, 0.38040077, 0.24778876, 0.38755082, 0.44501033, 0.36195828, 0.51158335, 0.42879438, 0.2588698, 0.46723188, 0.48340922, 0.49867308, 0.36013094, 0.47497761, 0.46174793, 0.38857972, 0.48098565, 0.46754799, 0.46510568, 0.34487737, 0.5009822, 0.56397328, 0.3543065, 0.40673866, 0.4613312, 0.38905596, 0.46315928, 0.28830975, 0.44983053, 0.47087864, 0.48292533, 0.32425203, 0.37115982, 0.32180676, 0.48643509, 0.39230303, 0.40647063, 0.54763232, 0.46265686, 0.28534676, 0.46693282, 0.31640954, 0.31168794, 0.36602008, 0.34811217, 0.24229468, 0.36702835, 0.40362387, 0.40479113, 0.13872621, 0.26345273, 0.41538197, 0.56689326, 0.41566561, 0.3762477, 0.49340067, 0.4394734, 0.37629781, 0.20504412, 0.39374825, 0.52972776, 0.38273825, 0.29761294, 0.47664454, 0.45938757, 0.45487454, 0.38555406, 0.4617614, 0.48428613, 0.41758518, 0.33610977, 0.13430649, 0.38886484, 0.17901085, 0.56204113, 0.29352569, 0.48553454, 0.518151, 0.50960812, 0.52409257, 0.42182042, 0.4185198, 0.3565483, 0.5104222, 0.44122936, 0.31683126, 0.46296244, 0.25652411, 0.49524575, 0.26125044, 0.47638072, 0.33925113, 0.44083941, 0.50694569, 0.54312653, 0.47062182, 0.44645908, 0.34174553, 0.60311544, 0.34104401, 0.40654912, 0.56998111, 0.34448869, 0.27507225, 0.59248512, 0.38521706, 0.37082996, 0.50615733, 0.38680788, 0.39427843, 0.30597846, 0.30645402, 0.21187443, 0.38037305, 0.38197224, 0.38764624, 0.37678424, 0.45554552, 0.33597934, 0.41605184, 0.45224793, 0.57240001, 0.40420628, 0.63715923, 0.48389614, 0.54798964, 0.46764357, 0.40435277, 0.21885673, 0.43905627, 0.45319166, 0.43038713, 0.40153829, 0.53959454, 0.24254268, 0.43926322, 0.50571213, 0.43943736, 0.41979652, 0.39291892, 0.31916475, 0.40932763, 0.61014458, 0.51960717, 0.40173633, 0.31974675, 0.25871366, 0.39317954, 0.42113008, 0.40788178, 0.54631586, 0.46935517, 0.28729743, 0.27599778, 0.31264138, 0.40299512, 0.2628075, 0.48508478, 0.28781431, 0.5783559, 0.47317538, 0.51010197, 0.55139271, 0.2346785, 0.43046587, 0.32553033, 0.2607733, 0.55785771, 0.249442, 0.23454964, 0.37076487, 0.42075005, 0.3818002, 0.3748194, 0.15974843, 0.20430708, 0.2651121, 0.40723294, 0.46314029, 0.4239376, 0.35839274, 0.42358318, 0.40613808, 0.48996164, 0.41849399, 0.35702307, 0.33902944, 0.29516511, 0.60558804, 0.21477395, 0.38389937, 0.38550857, 0.42728654, 0.40582218, 0.40652892, 0.31927979, 0.51823564, 0.26512122, 0.28237144, 0.49584295, 0.55198832, 0.14686962, 0.49377493, 0.52149058, 0.31991581, 0.3914851, 0.40830018, 0.15219631, 0.44201755, 0.25114049, 0.44105472, 0.37318572, 0.33555655, 0.25136385, 0.47129117, 0.29239281, 0.21258366, 0.55361937, 0.24602233, 0.44726495, 0.37877715, 0.52219122, 0.45435939, 0.50351221, 0.41720265, 0.43115457, 0.58818605, 0.39179413, 0.45514054, 0.40570764, 0.47853393, 0.44524242, 0.20824962, 0.31367051, 0.49445672, 0.56064673, 0.41090776, 0.47004423, 0.47597625, 0.4550135, 0.38420536, 0.46345875, 0.39640231, 0.42337578, 0.19354813, 0.37504802, 0.45031096, 0.29075096, 0.51989901, 0.3791604, 0.44155998, 0.2981352, 0.46158244, 0.35772838, 0.40761253, 0.35887065, 0.33801128, 0.4497198, 0.39714028, 0.3629864, 0.56414814, 0.35703518, 0.22267849, 0.31838847, 0.22882842, 0.49835933, 0.5385183, 0.42366345, 0.46814246, 0.34050133, 0.48873664, 0.54412422, 0.37726149, 0.15357791, 0.43701353, 0.40744805, 0.5602257, 0.617183, 0.44776676, 0.41123989, 0.40002999, 0.34421012, 0.22006825, 0.47735859, 0.32814275, 0.39013785, 0.49806074, 0.24318069, 0.24219131, 0.49470545, 0.51830093, 0.41392418, 0.27543923, 0.44216836, 0.37235984, 0.36905458, 0.38657276, 0.51229759, 0.23054795, 1.0, 0.47911198, 0.52175571, 0.47076358, 0.28385831, 0.33544588, 0.31778793, 0.48461983, 0.35952161, 0.33344736, 0.30989103, 0.3949117, 0.37819282, 0.37231449, 0.46012684, 0.32059956, 0.40391387, 0.50372852, 0.39326237, 0.54550083, 0.38429373, 0.36475192, 0.37983694, 0.54986948, 0.45329855, 0.36710511, 0.27704582, 0.38186398, 0.40364581, 0.49974917, 0.20705893, 0.5379345, 0.28266112, 0.48529591, 0.61444431, 0.28598076, 0.43196635, 0.43975012, 0.4466945, 0.43548002, 0.38582607, 0.54147148, 0.43144955, 0.55537415, 0.20585914, 0.22995888, 0.30973131, 0.36881204, 0.35709276, 0.46930278, 0.25294084, 0.53985943, 0.27390313, 0.30005384, 0.20799117, 0.24131116, 0.31473799, 0.27487912, 0.30930793, 0.30604629, 0.33609347]
463

In [100]:
denrat = 0 
for i in range(0, len(row[8])):
    denrat += (row[10][i]**row[1]) * (row[8][i]**row[3]) * (row[12][i]**row[2])
    
print("calculated denrat: ", denrat)
print("denrat: ", row[5])

calculated denrat:  79.78319783646555
denrat:  79.78319783444225

In [118]:
print("simh/siml: ", sum(row[12]/row[11]))

simh/siml:  544.4021782909762

### infinity calculations

In [111]:
df = pd.read_csv('beta/beta_CBM_with_rep_143316_145000.csv')
row = df.iloc[107][1:].tolist()
row

[26,
 132.15805337390933,
 17303882.123618405,
 -689103.0044546673,
 2.840987742861856e+99,
 1.5969242909864317e+122,
 1.7790372147867812e-23,
 0.1111,
 '[1.000e-04 1.000e-04 1.000e-04 1.111e-01 1.000e-04 1.111e-01 1.000e-04\n 1.111e-01 1.111e-01 1.111e-01 1.000e-04 2.222e-01 1.000e-04 1.000e-04\n 1.111e-01 1.000e-04 1.000e-04 1.000e-04 1.111e-01 1.111e-01 1.000e-04\n 1.000e-04 1.111e-01 1.000e-04 2.222e-01 1.111e-01 1.111e-01 1.000e-04\n 1.111e-01 2.222e-01 1.000e-04 1.111e-01 2.222e-01 1.111e-01 1.111e-01\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.111e-01 1.111e-01 1.000e-04\n 1.000e-04 1.111e-01 1.111e-01 1.000e-04 1.111e-01 1.111e-01 1.111e-01\n 1.111e-01 3.333e-01 2.222e-01 2.222e-01 1.111e-01 2.222e-01 1.111e-01\n 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01 1.000e-04 1.111e-01\n 1.111e-01 2.222e-01 3.333e-01 1.111e-01 1.000e-04 1.000e-04 1.111e-01\n 1.111e-01 1.000e-04 1.111e-01 2.222e-01 1.111e-01 1.111e-01 1.111e-01\n 1.111e-01 1.111e-01 3.333e-01 1.111e-01 2.222e-01 1.111e-01 1.111e-01\n 1.111e-01 1.111e-01 2.222e-01 1.111e-01 1.111e-01 2.222e-01 3.333e-01\n 1.111e-01 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01 1.111e-01\n 1.111e-01 1.111e-01 1.000e-04 1.000e-04 1.111e-01 1.000e-04 2.222e-01\n 1.000e-04 1.111e-01 2.222e-01 2.222e-01 1.000e-04 3.333e-01 1.111e-01\n 1.111e-01 1.111e-01 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.000e-04\n 1.000e-04 1.111e-01 1.111e-01 2.222e-01 1.111e-01 3.333e-01 2.222e-01\n 2.222e-01 2.222e-01 1.000e-04 1.000e-04 1.111e-01 1.000e-04 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.111e-01 1.000e-04 1.000e-04\n 1.111e-01 2.222e-01 1.111e-01 1.111e-01 1.000e-04 1.000e-04 1.111e-01\n 1.000e-04 1.111e-01 1.111e-01 1.000e-04 1.111e-01 2.222e-01 1.000e-04\n 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 1.111e-01 1.111e-01 1.111e-01 1.111e-01 1.111e-01 1.111e-01\n 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01 1.000e-04 1.111e-01\n 1.111e-01 2.222e-01 1.111e-01 1.111e-01 2.222e-01 1.000e-04 1.000e-04\n 1.111e-01 1.111e-01 3.333e-01 1.111e-01 1.818e-01 1.000e-04 1.000e-04\n 1.111e-01 2.222e-01 1.000e-04 2.222e-01 1.111e-01 1.111e-01 1.111e-01\n 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01 2.222e-01 1.111e-01\n 1.111e-01 1.000e-04 1.000e-04 1.000e-04 1.111e-01 2.222e-01 1.111e-01\n 1.000e-04 1.111e-01 2.222e-01 1.111e-01 1.000e-04 1.111e-01 1.000e-04\n 1.000e-04 1.000e-04 2.222e-01 2.222e-01 1.111e-01 1.000e-04 1.000e-04\n 1.111e-01 1.000e-04 2.222e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01\n 1.000e-04 1.000e-04 2.222e-01 1.111e-01 1.000e-04 1.111e-01 2.222e-01\n 1.111e-01 2.222e-01 1.000e-04 1.111e-01 1.111e-01 1.111e-01 1.111e-01\n 3.333e-01 1.111e-01 2.222e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01\n 1.000e-04 1.111e-01 1.000e-04 1.000e-04 1.000e-04 3.333e-01 1.000e-04\n 1.111e-01 1.000e-04 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.000e-04\n 1.000e-04 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01 1.111e-01\n 1.111e-01 1.111e-01 1.111e-01 1.000e-04 2.222e-01 1.000e-04 1.000e-04\n 1.000e-04 3.333e-01 2.222e-01 1.111e-01 1.000e-04 1.000e-04 1.000e-04\n 1.111e-01 3.333e-01 1.000e-04 1.000e-04 1.111e-01 2.222e-01 3.333e-01\n 3.333e-01 3.333e-01 2.222e-01 3.333e-01 3.333e-01 1.111e-01 3.333e-01\n 3.333e-01 2.222e-01 1.111e-01 1.000e-04 1.111e-01 3.333e-01 1.111e-01\n 2.222e-01 1.111e-01 1.111e-01 2.222e-01 1.111e-01 2.222e-01 1.000e+00\n 4.444e-01 4.444e-01 2.222e-01 1.111e-01 2.222e-01 2.000e-01 2.222e-01\n 1.111e-01 1.111e-01 2.222e-01 2.222e-01 2.222e-01 1.111e-01 1.111e-01\n 2.222e-01 1.111e-01 1.111e-01 2.222e-01 1.111e-01 3.333e-01 1.111e-01\n 1.111e-01 1.000e-04 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.111e-01\n 3.333e-01 1.111e-01 1.111e-01 1.111e-01 1.111e-01 1.000e-04 2.222e-01\n 2.222e-01 3.333e-01 1.000e-04 1.111e-01 1.000e-04 2.222e-01 1.111e-01\n 1.000e-04 1.111e-01 1.000e-04 2.222e-01 1.111e-01 1.111e-01 1.111e-01\n 1.111e-01 1.000e-04 1.000e-04 1.000e-04 1.000e-04 1.111e-01 1.111e-01\n 1.111e-01 1.000e-04 2.222e-01 1.111e-01 1.000e-04 1.111e-01 1.000e-04\n 1.111e-01 1.111e-01 1.000e-04 3.333e-01 1.000e-04 1.000e-04 1.000e-04\n 1.000e-04 2.222e-01 2.222e-01 1.000e-04 1.000e-04 1.111e-01 1.000e-04\n 1.111e-01 1.000e-04 1.111e-01 2.222e-01 1.000e-04 1.111e-01 1.111e-01\n 1.000e-04 1.111e-01 1.111e-01 1.000e-04 1.000e-04 1.000e-04 3.333e-01\n 3.333e-01 1.111e-01 1.111e-01 1.111e-01 1.111e-01 1.000e-04 1.000e-04\n 1.111e-01 1.111e-01 1.111e-01 2.222e-01 1.000e-04 1.111e-01 1.111e-01\n 1.000e-04 2.222e-01 2.222e-01 1.111e-01 1.111e-01 1.111e-01 1.000e-04\n 9.090e-02 1.000e-04 1.000e-04 1.000e-04 1.000e-04 2.222e-01 1.000e-04\n 1.000e-04 1.111e-01 1.000e-04 2.222e-01 1.000e-04 1.111e-01 1.000e-04\n 1.000e-04 2.222e-01 1.111e-01 1.000e-04 1.111e-01 1.111e-01 2.222e-01\n 2.222e-01 2.222e-01 1.000e-04 1.000e-04 1.111e-01 1.111e-01 2.222e-01\n 2.222e-01 2.222e-01 2.222e-01 3.333e-01 1.111e-01 2.222e-01 1.000e-04\n 1.111e-01]',
 5.656324398,
 '[5.54479829 5.40041537 5.71416289 4.95691723 5.19427562 5.36416061\n 6.4261461  5.84517062 6.01239891 5.81312644 6.57583615 5.36663211\n 7.27868644 5.80313196 5.84991915 4.87676037 6.63150079 6.52730735\n 5.38246012 7.36622693 6.27319301 6.52393588 6.02186668 7.11940024\n 5.77813388 4.91087509 5.48689924 5.31324274 5.42827413 5.90912687\n 5.34874867 5.83892776 5.03831808 6.47724255 6.71047101 6.15191934\n 6.95347854 5.40648568 4.9575594  5.84937826 4.87166049 5.80942435\n 5.58832438 6.02804311 6.22570901 5.41009701 6.36702961 6.12305154\n 5.40936834 5.80587722 5.92785316 4.34588321 6.70466853 5.66047842\n 5.67599086 7.01314336 5.82700462 6.99145703 4.98628344 4.46372879\n 5.34309729 5.24019718 6.13538329 6.0950762  4.98597405 6.82758559\n 4.5937954  5.35425638 5.14961934 5.7629695  5.6749759  5.0944292\n 6.34660546 5.01198044 6.29438156 5.16478099 5.33323965 6.05355398\n 5.4567546  6.33169629 5.3132174  4.89617335 6.67904722 6.51714732\n 6.00734017 6.15811632 6.40422836 5.1067313  5.42952458 5.98034976\n 5.74138405 6.39803797 5.72680705 5.69702959 5.00798662 4.75673497\n 7.40325542 6.70698374 4.13436839 6.93246286 5.22334535 6.34802277\n 7.25611403 6.98735549 5.8648432  6.08020714 6.01842169 4.70769789\n 5.25922823 6.32439606 6.4776833  6.29606092 4.74550419 6.4396388\n 5.16028241 6.18352152 6.64085425 5.81821203 5.53780525 4.97979413\n 6.36366029 6.13956584 5.40300206 5.49800161 5.93662582 5.73324703\n 5.5591762  5.53151085 5.22067805 5.89118162 5.16926875 7.34481426\n 6.60415431 5.81714343 6.59752483 5.421176   7.02917652 5.16993294\n 5.41156079 6.05982081 6.84972718 5.86263101 4.30033457 6.31934657\n 6.22332536 6.32233364 4.29673099 5.20884966 5.69120442 5.34520312\n 6.03987712 6.83232481 5.91434792 5.09528445 5.25936688 6.36583846\n 6.23189196 4.54084231 4.93771343 5.47526285 6.30195579 5.59729141\n 5.65709316 5.62931376 5.2365423  5.59953703 5.73562604 4.81622804\n 5.74121071 5.69974236 5.6539762  4.53131283 6.0966139  5.75274123\n 5.42877766 5.30317661 5.23774475 6.38789858 6.50909199 6.38458152\n 5.30144889 5.48215154 6.44552325 6.01428148 5.80200431 6.00100423\n 5.25839062 6.1191846  6.06158667 4.55894845 7.39671054 5.99387075\n 7.98965008 5.42222367 5.72994274 5.52378027 5.28499889 5.12002084\n 4.82558189 6.51956353 7.19745311 5.36467667 5.15519024 4.69350711\n 5.70257958 6.55394513 5.22457968 5.56621823 4.35285756 6.77461447\n 5.19281826 5.88303424 5.85594476 6.17394082 6.5534405  5.72304581\n 4.67605313 4.67003236 6.67546488 5.90347634 5.97693842 6.32090595\n 5.66947123 4.73326951 5.87598562 5.12563739 6.72395708 5.25925214\n 6.27733182 5.89522027 5.26914153 4.58063991 5.98910839 5.79519503\n 5.50136056 5.51662262 5.51244958 5.55509566 5.17378047 5.29660816\n 5.36434083 5.91173061 8.40582899 6.29051474 4.91820863 5.34128611\n 5.05999863 5.04717748 5.51528026 5.8723754  6.64058866 5.28218465\n 5.30666516 5.67333338 5.21399827 4.84604625 5.79285026 5.20351154\n 6.34759598 4.94896038 4.9844733  6.74986543 6.40192655 6.27941368\n 6.50045384 5.97775423 5.30054549 6.0265492  6.09035471 5.82972885\n 6.77684605 6.27403956 6.21093915 5.22988141 5.24813518 5.34251151\n 5.55104113 5.46032341 5.45678191 5.9647328  4.74836636 5.17316295\n 5.21287181 5.65358681 4.98490069 5.85768341 6.24711561 6.33101933\n 6.16528113 6.06514446 6.01909426 5.88628481 4.71569422 4.86887357\n 5.92109627 5.86740973 6.00263338 5.58192805 6.25042049 5.98829937\n 5.46087079 7.92691552 4.60659631 5.61970467 6.32053967 6.61154297\n 6.10484819 5.22249797 6.31138805 5.30314204 6.53451663 5.88079931\n 6.1797195  5.35560475 5.58063079 6.42252681 5.23339213 5.44040999\n 6.2976058  5.8927639  5.00730387 4.92727795 5.30037154 4.85464605\n 5.21953999 5.68211438 6.03109081 5.2925241  5.85883485 6.56862865\n 6.40924176 6.76646341 5.068364   5.64832097 6.2387933  7.101132\n 4.49780013 4.621249   3.92931673 5.76409241 5.6563244  5.50684178\n 5.68899257 6.52619707 6.04796568 5.4965159  5.70385517 5.82336205\n 5.41027096 6.53599766 5.1590285  5.60137761 6.7887631  6.38005632\n 5.53223317 6.05460386 6.92417287 5.70115767 6.54277254 5.54581041\n 6.17749985 5.1888582  5.58390577 5.61302636 5.09154034 5.60361632\n 5.6658248  5.59460578 5.85380525 6.61507849 5.33162567 5.34684568\n 6.12976302 5.35852874 6.06375281 6.28164913 6.14113578 4.8769795\n 4.83454786 6.08084034 5.78537611 5.76888884 5.31226201 5.49266263\n 5.87640203 6.13540142 5.48775755 5.52855421 5.03187281 6.40307057\n 6.23145965 6.72486439 6.08194504 5.25062734 5.20892215 5.34137714\n 4.94463564 5.62374431 5.57888551 5.42137191 5.6849898  6.01822018\n 6.38952206 5.02977731 5.88589528 5.79337125 4.73203975 4.08845504\n 5.5450113  6.39341672 5.38398941 4.66830203 4.85497367 6.76776835\n 6.2297581  5.57345298 5.53606327 5.90222162 5.62709434 5.48204277\n 5.63386924 5.41780372 5.61881972 5.78342259 5.50157956 5.59878941\n 6.33861504 4.93445805 5.47692723 5.14602565 5.8536605  5.47753653\n 5.4461751  6.74554898 4.52057523 5.15610676 6.26570392 7.86615585\n 5.02871355 5.49635113 5.58929711 6.38306367 5.85059294 5.19362542\n 4.27870788 5.56168919 5.94341091 6.42539563 6.22546462 5.41884962\n 6.53817281 5.8220294  6.31354138 6.37252151 6.51178019 6.79845506\n 8.14512647 6.53085142 7.28454499 8.1286163  5.81842254 6.71528817\n 6.14479208]',
 0.3901601952380003,
 '[0.42624669 0.53603838 0.54988081 0.72508962 0.58511665 0.77411467\n 0.39645757 0.57147559 0.26153998 0.51450555 0.26495422 0.47788962\n 0.39282436 0.33515728 0.319476   0.28663773 0.38962146 0.33718425\n 0.45025147 0.18672036 0.43681885 0.40361042 0.5958706  0.43869542\n 0.56374075 0.46316956 0.48361173 0.50106184 0.57987762 0.52316787\n 0.30212062 0.4179793  0.4064674  0.33747373 0.47032432 0.48721297\n 0.37354141 0.51431073 0.18263005 0.44793535 0.46708036 0.28328767\n 0.75548138 0.56136967 0.47184578 0.37095835 0.42937479 0.4515367\n 0.50707836 0.57305284 0.39087513 0.36283286 0.26171569 0.68621928\n 0.59933699 0.34566265 0.25754594 0.33200347 0.56162718 0.66057855\n 0.43666117 0.75013669 0.55736928 0.41372131 0.61137597 0.38270644\n 0.30803194 0.50007092 0.4935137  0.59240709 0.70023229 0.71316446\n 0.42355391 0.63023387 0.48884683 0.59344969 0.49707495 0.45526759\n 0.39009019 0.59476417 0.48232451 0.67224492 0.31819523 0.3771648\n 0.40135298 0.44502473 0.57517871 0.58155997 0.55667586 0.4112138\n 0.44262432 0.36511869 0.29979016 0.49275992 0.44461133 0.65744245\n 0.16587999 0.41560777 0.38611983 0.18254761 0.23235593 0.45753841\n 0.33619875 0.35297598 0.46319027 0.42002981 0.33082093 0.40078793\n 0.67350598 0.46924979 0.36504606 0.33225348 0.50838662 0.53136337\n 0.60942774 0.46271428 0.46854677 0.4957473  0.513421   0.67331645\n 0.49685029 0.54957552 0.68831699 0.54893537 0.61316417 0.34483451\n 0.33688895 0.31096009 0.51707049 0.57434117 0.60250888 0.43875974\n 0.37307638 0.37501963 0.52246889 0.38224039 0.4189909  0.43523927\n 0.44498951 0.38509522 0.37693821 0.45921046 0.3887464  0.40994075\n 0.48841385 0.29825758 0.63395027 0.4995048  0.38857307 0.61864589\n 0.52957838 0.42682828 0.12760364 0.20775467 0.3997579  0.41477267\n 0.43381209 0.55110989 0.64975373 0.74587753 0.36102037 0.39108157\n 0.30969887 0.6137873  0.50545671 0.3614452  0.54827404 0.61228158\n 0.42235906 0.43058667 0.29637635 0.6552012  0.47076591 0.57641266\n 0.24068857 0.51861101 0.38952092 0.41099094 0.42655372 0.43734605\n 0.5561646  0.53620051 0.42430505 0.31582279 0.43780259 0.56755653\n 0.60528055 0.49372101 0.47362929 0.4579917  0.30004156 0.30733127\n 0.12208007 0.34554603 0.23041846 0.49847978 0.57863095 0.49822796\n 0.40066344 0.45715901 0.33613006 0.40208295 0.40027718 0.5502698\n 0.50037592 0.40239407 0.59321398 0.40270187 0.27334307 0.35835308\n 0.64474388 0.45252298 0.47313484 0.18760133 0.43050727 0.32620637\n 0.51407049 0.37484803 0.32136806 0.37418922 0.64524066 0.47981725\n 0.39670312 0.68867148 0.6206288  0.61509871 0.36471244 0.42334751\n 0.36237216 0.44870501 0.48894171 0.16027271 0.52915715 0.68993032\n 0.58146414 0.54871538 0.41967622 0.67987423 0.44435316 0.42805616\n 0.51295573 0.61026588 0.19093441 0.34505226 0.69126004 0.60630516\n 0.5155345  0.6859887  0.64730626 0.35215974 0.42957141 0.28624399\n 0.55093752 0.45307886 0.58777969 0.23085854 0.33398629 0.6629529\n 0.50952409 0.75036997 0.42942546 0.22076153 0.42703605 0.40452719\n 0.28767645 0.46399016 0.20441966 0.59532142 0.54103394 0.55811747\n 0.39898578 0.33709683 0.37622193 0.67786033 0.37859113 0.72123876\n 0.37203715 0.27259679 0.28767115 0.27967259 0.53732489 0.41534657\n 0.63153069 0.61880637 0.69282556 0.43050349 0.40473774 0.36435384\n 0.42104874 0.43918951 0.47205774 0.38525873 0.24460633 0.61163027\n 0.48893949 0.39323623 0.52889164 0.55780326 0.49950876 0.45313537\n 0.23463374 0.08880233 0.43349459 0.55024423 0.3632493  0.4369264\n 0.46564275 0.23193061 0.4801118  0.55382771 0.39405579 0.54933247\n 0.25230492 0.55245519 1.         0.52085592 0.55690297 0.33957253\n 0.40977268 0.18949832 0.61187369 0.26321631 0.51890463 0.4960296\n 0.66606751 0.43446163 0.43135188 0.40724436 0.37838729 0.42420495\n 0.40674936 0.36507402 0.39686147 0.52726714 0.53363968 0.26709305\n 0.4253064  0.52208219 0.46393447 0.54068318 0.3901602  0.48041094\n 0.38414591 0.30366411 0.49385898 0.43079138 0.49358385 0.5667347\n 0.59053715 0.46663585 0.43255868 0.45431541 0.34939503 0.47836772\n 0.53392062 0.46142648 0.39746041 0.61555996 0.29067525 0.34426449\n 0.52754906 0.67083599 0.47944517 0.35588459 0.5238242  0.25698475\n 0.47286094 0.52564174 0.47282567 0.49146472 0.46566563 0.56746717\n 0.40847046 0.55735409 0.42574704 0.51592546 0.4020308  0.38868236\n 0.49427794 0.47097946 0.38832296 0.62291874 0.52649288 0.53940341\n 0.36884795 0.34249412 0.44245145 0.45215042 0.50456995 0.35888772\n 0.4658572  0.36194836 0.43911732 0.50216848 0.39268884 0.3534602\n 0.69548835 0.65860942 0.32721134 0.47676558 0.58513996 0.48125147\n 0.37318572 0.62445532 0.35957231 0.53783431 0.34378711 0.71079306\n 0.45824829 0.50161295 0.50919623 0.42694681 0.52898089 0.32333878\n 0.3472986  0.56816753 0.51277911 0.47838978 0.37893073 0.51005862\n 0.62880207 0.6631693  0.69355347 0.59781382 0.64816333 0.46208339\n 0.42633208 0.3971633  0.4362974  0.61654362 0.48531987 0.41697631\n 0.39354506 0.31058324 0.37162975 0.53692603 0.40289698 0.20905109\n 0.46168519 0.58964277 0.57271265 0.45898592 0.37250013 0.53194629\n 0.56184316 0.54763402 0.53986292 0.27886335 0.35620947 0.45716398\n 0.42619531 0.53214007 0.55882771 0.45809015 0.46626679 0.508258\n 0.21714879 0.389735   0.35895975 0.43232996 0.47542013 0.465357\n 0.34390056]']

In [112]:
# k	 beta_freq	beta_sem	beta_phon	numrat	denrat	num/den	phonl	phonh	freql	freqh	siml	simh
# 0      1          2           3       4       5       6       7       8       9       10      11      12
'''
if phoncue in ["local","global"]:
    numrat = pow(freql[k],beta[0])*pow(phonl[k],beta[2])*pow(siml[k],beta[1])
    denrat = sum(pow(freqh[k],beta[0])*pow(phonh[k],beta[2])*pow(simh[k],beta[1]))
else:
    numrat = pow(freql[k],beta[0]) * pow(siml[k],beta[1])
    denrat = sum(pow(freqh[k],beta[0]) * pow(simh[k],beta[1]))
'''

numrat = (row[9]**row[1]) * (row[7]**row[3]) * (row[11]**row[2])
print("calculated numrat: ", numrat)
print("numrat: ", row[4])

calculated numrat:  nan
numrat:  2.840987742861856e+99

/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_5885/2279429325.py:12: RuntimeWarning: overflow encountered in scalar power
  numrat = (row[9]**row[1]) * (row[7]**row[3]) * (row[11]**row[2])
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_5885/2279429325.py:12: RuntimeWarning: invalid value encountered in scalar multiply
  numrat = (row[9]**row[1]) * (row[7]**row[3]) * (row[11]**row[2])

In [113]:
row[8] = row[8][1:-1].replace('\n', ' ').split(' ')
row[8] = [i for i in row[8] if i != '']
row[8] = [float(i) for i in row[8]]
row[10] = row[10][1:-1].replace('\n', ' ').split(' ')
row[10] = [i for i in row[10] if i != '']
row[10] = [float(i) for i in row[10]]
row[12] = row[12][1:-1].replace('\n', ' ').split(' ')
row[12] = [i for i in row[12] if i != '']
row[12] = [float(i) for i in row[12]]

In [114]:
denrat = 0 
for i in range(0, len(row[8])):
    denrat += (row[10][i]**row[1]) * (row[8][i]**row[3]) * (row[12][i]**row[2])
    
print("calculated denrat: ", denrat)
print("denrat: ", row[5])

calculated denrat:  nan
denrat:  1.5969242909864317e+122

/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_5885/255474500.py:3: RuntimeWarning: overflow encountered in scalar power
  denrat += (row[10][i]**row[1]) * (row[8][i]**row[3]) * (row[12][i]**row[2])
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_5885/255474500.py:3: RuntimeWarning: invalid value encountered in scalar multiply
  denrat += (row[10][i]**row[1]) * (row[8][i]**row[3]) * (row[12][i]**row[2])