In [1]:
import pandas as pd
import numpy as np

/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [88]:
participant_truncation = pd.read_csv("analysis/outputs/length_matched_items.csv")

old_participant_truncation = pd.read_csv("analysis/outputs/length_matched_items.csv")
old_part_dict = [[x, y] for x, y in zip(old_participant_truncation['ID_NH'], old_participant_truncation['ID_CI'])]


rep_data = pd.read_csv('forager/data/fluency_lists/participant_data/transformed-data.csv')
no_rep_data = pd.read_csv("forager/data/fluency_lists/participant_data/no_rep_data.csv")
participant_order = pd.Series(no_rep_data['ID']).drop_duplicates().tolist()
new_participant_truncation = pd.DataFrame(columns=['NH', 'ID_NH', 'n_NH', 'CI', 'ID_CI', 'n_CI', 'n_final'])

for part in old_part_dict: 
    df = no_rep_data.groupby('ID')
    NH = part[0]
    CI = part[1]
    row = ['NH', NH, len(df.get_group(NH)), 'CI', CI, len(df.get_group(CI)), min(len(df.get_group(NH)), len(df.get_group(CI)))]
    new_participant_truncation.loc[len(new_participant_truncation)] = row
    
new_participant_truncation.to_csv('analysis/outputs/new_length_matched_items.csv', index=False)

In [89]:

truncated_data_path = 'forager/data/fluency_lists/participant_data/truncated_data.csv'

In [90]:
participant_truncation = pd.read_csv("analysis/outputs/new_length_matched_items.csv")
participant_truncation

    NH    ID_NH  n_NH  CI    ID_CI  n_CI  n_final
0   NH  CAF-657    28  CI  SGO-159    36       28
1   NH  CCD-722    29  CI  SKE-234    28       28
2   NH  CAV-678    28  CI  SNT-310    27       27
3   NH  CBP-707    28  CI  SIU-211    23       23
4   NH  CBM-702    25  CI  SMK-401    23       23
5   NH  CAM-666    25  CI  SOQ-329    23       23
6   NH  CBH-693    22  CI  SPX-452    22       22
7   NH  CBS-711    24  CI  SVA-563    19       19
8   NH  CCL-730    23  CI  SNY-315    20       20
9   NH  CDG-753    23  CI  SPC-340    20       20
10  NH  CAQ-672    23  CI  SPV-450    19       19
11  NH  CAR-673    23  CI  SUV-558    19       19
12  NH  CAY-681    21  CI  SVY-587    18       18
13  NH  CBJ-697    23  CI  SNI-300    18       18
14  NH  CCH-726    23  CI  SNV-312    18       18
15  NH  CAS-674    21  CI  SRR-498    18       18
16  NH  CBD-686    21  CI  SIZ-390    17       17
17  NH  CAJ-663    20  CI  SPA-338    16       16
18  NH  CBL-698    19  CI  SPL-436    16       16
19  NH  CAP-671    19  CI  SZA-781    16       16
20  NH  CBF-691    19  CI  SNR-308    16       16
21  NH  CDM-759    19  CI  SRF-483    16       16
22  NH  CDU-767    19  CI  SSG-520    13       13
23  NH  CBW-715    18  CI  SUG-544    14       14
24  NH  CCF-724    18  CI  SUT-556    15       15
25  NH  CCX-744    18  CI  SVH-570    15       15
26  NH  CDR-764    17  CI  SOE-320    13       13
27  NH  CCC-721    15  CI  SSZ-539    13       13
28  NH  CCB-720    14  CI  SOX-335    11       11
29  NH  CDH-754    13  CI  SPH-344    10       10

In [91]:
NH_participants = participant_truncation['ID_NH'].tolist()
CI_participants = participant_truncation['ID_CI'].tolist()
n_final = participant_truncation['n_final'].tolist()

In [92]:
trunc_dict = {} 
for i in range(len(NH_participants)):
    trunc_dict[NH_participants[i]] = n_final[i]
    trunc_dict[CI_participants[i]] = n_final[i]
print(trunc_dict)

{'CAF-657': 28, 'SGO-159': 28, 'CCD-722': 28, 'SKE-234': 28, 'CAV-678': 27, 'SNT-310': 27, 'CBP-707': 23, 'SIU-211': 23, 'CBM-702': 23, 'SMK-401': 23, 'CAM-666': 23, 'SOQ-329': 23, 'CBH-693': 22, 'SPX-452': 22, 'CBS-711': 19, 'SVA-563': 19, 'CCL-730': 20, 'SNY-315': 20, 'CDG-753': 20, 'SPC-340': 20, 'CAQ-672': 19, 'SPV-450': 19, 'CAR-673': 19, 'SUV-558': 19, 'CAY-681': 18, 'SVY-587': 18, 'CBJ-697': 18, 'SNI-300': 18, 'CCH-726': 18, 'SNV-312': 18, 'CAS-674': 18, 'SRR-498': 18, 'CBD-686': 17, 'SIZ-390': 17, 'CAJ-663': 16, 'SPA-338': 16, 'CBL-698': 16, 'SPL-436': 16, 'CAP-671': 16, 'SZA-781': 16, 'CBF-691': 16, 'SNR-308': 16, 'CDM-759': 16, 'SRF-483': 16, 'CDU-767': 13, 'SSG-520': 13, 'CBW-715': 14, 'SUG-544': 14, 'CCF-724': 15, 'SUT-556': 15, 'CCX-744': 15, 'SVH-570': 15, 'CDR-764': 13, 'SOE-320': 13, 'CCC-721': 13, 'SSZ-539': 13, 'CCB-720': 11, 'SOX-335': 11, 'CDH-754': 10, 'SPH-344': 10}

In [106]:
trunc_df = pd.DataFrame(columns=['ID', 'Word'])
trunc_df

Empty DataFrame
Columns: [ID, Word]
Index: []

In [107]:
participant_order = pd.Series(no_rep_data['ID']).drop_duplicates().tolist()
participant_order

['CAF-657',
 'CAJ-663',
 'CAM-666',
 'CAP-671',
 'CAQ-672',
 'CAR-673',
 'CAS-674',
 'CAV-678',
 'CAY-681',
 'CBD-686',
 'CBF-691',
 'CBH-693',
 'CBJ-697',
 'CBL-698',
 'CBM-702',
 'CBP-707',
 'CBS-711',
 'CBW-715',
 'CCB-720',
 'CCC-721',
 'CCD-722',
 'CCF-724',
 'CCH-726',
 'CCL-730',
 'CCX-744',
 'CDG-753',
 'CDH-754',
 'CDM-759',
 'CDR-764',
 'CDU-767',
 'SGO-159',
 'SIU-211',
 'SIZ-390',
 'SKE-234',
 'SMK-401',
 'SNI-300',
 'SNR-308',
 'SNT-310',
 'SNV-312',
 'SNY-315',
 'SOE-320',
 'SOQ-329',
 'SOX-335',
 'SPA-338',
 'SPC-340',
 'SPH-344',
 'SPL-436',
 'SPV-450',
 'SPX-452',
 'SRF-483',
 'SRR-498',
 'SSG-520',
 'SSZ-539',
 'SUG-544',
 'SUT-556',
 'SUV-558',
 'SVA-563',
 'SVH-570',
 'SVY-587',
 'SZA-781']

In [109]:
for participant in participant_order: 
    df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)

    for i in range(trunc_dict[participant]):
        trunc_df.loc[len(trunc_df)] = df.loc[i]
trunc_df.to_csv('forager/data/fluency_lists/participant_data/truncated_data.csv', index=False)

/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)
/var/folders/s7/md5b66vn4l39df_j063nqlp00000gn/T/ipykernel_53081/3611779157.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df = no_rep_data.groupby(['ID']).get_group(participant).reset_index(drop=True)

In [115]:
trunc_df

           ID     Word
0     CAF-657   lizard
1     CAF-657      cat
2     CAF-657     hawk
3     CAF-657      dog
4     CAF-657   turtle
...       ...      ...
1083  SZA-781  bulldog
1084  SZA-781    puppy
1085  SZA-781   kitten
1086  SZA-781    goose
1087  SZA-781     duck

[1088 rows x 2 columns]

In [104]:
# double checking 
count = 0 
for part in participant_order: 
    df = trunc_df.groupby('ID').get_group(part).reset_index(drop=True)
    if len(df) != trunc_dict[part]: 
        count +=1
print(count)

0

In [116]:
no_rep_data = pd.read_csv("forager/data/fluency_lists/participant_data/no_rep_data.csv")
no_rep_data

           ID     Word
0     CAF-657   lizard
1     CAF-657      cat
2     CAF-657     hawk
3     CAF-657      dog
4     CAF-657   turtle
...       ...      ...
1185  SZA-781  bulldog
1186  SZA-781    puppy
1187  SZA-781   kitten
1188  SZA-781    goose
1189  SZA-781     duck

[1190 rows x 2 columns]

In [117]:
participant_truncation = pd.read_csv("analysis/outputs/new_length_matched_items.csv")
participant_truncation

    NH    ID_NH  n_NH  CI    ID_CI  n_CI  n_final
0   NH  CAF-657    28  CI  SGO-159    36       28
1   NH  CCD-722    29  CI  SKE-234    28       28
2   NH  CAV-678    28  CI  SNT-310    27       27
3   NH  CBP-707    28  CI  SIU-211    23       23
4   NH  CBM-702    25  CI  SMK-401    23       23
5   NH  CAM-666    25  CI  SOQ-329    23       23
6   NH  CBH-693    22  CI  SPX-452    22       22
7   NH  CBS-711    24  CI  SVA-563    19       19
8   NH  CCL-730    23  CI  SNY-315    20       20
9   NH  CDG-753    23  CI  SPC-340    20       20
10  NH  CAQ-672    23  CI  SPV-450    19       19
11  NH  CAR-673    23  CI  SUV-558    19       19
12  NH  CAY-681    21  CI  SVY-587    18       18
13  NH  CBJ-697    23  CI  SNI-300    18       18
14  NH  CCH-726    23  CI  SNV-312    18       18
15  NH  CAS-674    21  CI  SRR-498    18       18
16  NH  CBD-686    21  CI  SIZ-390    17       17
17  NH  CAJ-663    20  CI  SPA-338    16       16
18  NH  CBL-698    19  CI  SPL-436    16       16
19  NH  CAP-671    19  CI  SZA-781    16       16
20  NH  CBF-691    19  CI  SNR-308    16       16
21  NH  CDM-759    19  CI  SRF-483    16       16
22  NH  CDU-767    19  CI  SSG-520    13       13
23  NH  CBW-715    18  CI  SUG-544    14       14
24  NH  CCF-724    18  CI  SUT-556    15       15
25  NH  CCX-744    18  CI  SVH-570    15       15
26  NH  CDR-764    17  CI  SOE-320    13       13
27  NH  CCC-721    15  CI  SSZ-539    13       13
28  NH  CCB-720    14  CI  SOX-335    11       11
29  NH  CDH-754    13  CI  SPH-344    10       10

In [119]:
count = 0 
for i in range(len(participant_truncation)): 
    n_final = participant_truncation['n_final'][i]
    count += max(participant_truncation['n_NH'][i], participant_truncation['n_CI'][i]) - n_final
print(count)

102

In [120]:
print(1190 - 1088)

102

In [121]:
data = pd.read_csv("forager/data/fluency_lists/participant_data/truncated_data.txt", delimiter='\t')
data

           ID     Word
0     CAF-657   lizard
1     CAF-657      cat
2     CAF-657     hawk
3     CAF-657      dog
4     CAF-657   turtle
...       ...      ...
1083  SZA-781  bulldog
1084  SZA-781    puppy
1085  SZA-781   kitten
1086  SZA-781    goose
1087  SZA-781     duck

[1088 rows x 2 columns]